---
title: "Phylogenetic Analysis"
author: "MOL.923 Computerlabor Bioinformatik (WS 2024/25)"
date: "08/01/2025"
output: html_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Alignments und phylogenetische Bäume mit Webtools erstellen

Erzeugen Sie ein MSA von den Dateien *TTR_clean.fas* und *RAG2_clean.fas* mit *clustalOmega*, *mafft* oder *muscle5* (https://www.ebi.ac.uk/jdispatcher/msa).

* Betrachten Sie die Alignmente? Gibt es potientielle Probleme? Welche?

Benutzen Sie die Datei *concatenated_dna.fasta* um einen phylogenetischen Baum zu berechenen (http://iqtree.cibiv.univie.ac.at/). Benutzen Sie die Standardeinstellungen.

* Welches Model wurde verwendet?

* Sind die unterschiedlichen Familien (Katzen, Hunde, Bären, etc.) monophyletic?
* Sie können die Bäume mit (https://itol.embl.de/) anschauen!


## Bäume und Alignments in R visualisieren 

An den Computern im Übungsraum ist R / RStudio und die Pakete die wir benutzen schon installiert.
Hier wollen wir kurz zeigen welche Möglichkeiten Skripten zeigen. 


Öffnen Sie RStudio auf den Lab-Computern und kopieren Sie den folgenden Code in die Konsole (Console).
Zuerst laden wir zwei Packete die Phylogonien erstellen und bearbeiten. 
```{R, eval=TRUE}
library(ape)
library(phangorn)
```



Danach laden wir 3 Datensätze, einen phylogenetischen Baum, ein Alignment und eine Tabelle mit Information zu unseren Daten.  
```{R, eval=TRUE}
tree_file <- "https://raw.githubusercontent.com/KlausVigo/Mol504/refs/heads/main/iqtree/concatenated_dna.fasta.treefile"
align_file <- "https://raw.githubusercontent.com/KlausVigo/Mol504/refs/heads/main/data/concatenated_dna.fasta"
tab_file <- "https://raw.githubusercontent.com/KlausVigo/Mol504/refs/heads/main/data/cats_dogs.csv"

tree <-  read.tree(tree_file)
align <- read.phyDat(align_file, format="fasta")
tab <- read.csv(tab_file)
```

Wir können das ganze Alignment oder nur einen Ausschnitt visualisieren und wenn wir wollen als pdf oder einem anderen Fromat speichern. 
```{R, eval=TRUE}
par(mar=c(4,13,4,2))
image(align)
image(align[1:10, 251:300], show.bases=TRUE)
```

Wir können auch phylogenetische Bäume malen und haben dafür eine Menge Optionen.
```{R, eval=TRUE}
par(mar=c(1,1,1,1))
plot(tree, cex=.75)
```

Jetzt verwenden wir ein paar Farben um die unterschiedlichen Familien besser zu erkennen.   
```{R, eval=TRUE}
par(mar=c(1,1,1,1))
col <- c("green", "blue", "lightblue", "red", "orange", "brown", "yellow",      
         "darkgreen", "magenta")
family_color <- setNames(col, unique(tab$Family))
family_color

tip_color <- setNames(family_color[tab$Family], tab$Species)


tree <- midpoint(tree)

plot(tree, type="fan", tip.col=tip_color[tree$tip.label], cex=.5, show.node.label = TRUE)
add.scale.bar()
```

Die Funtion *plot.phylo*, wir können aber nur *plot* schreiben, hat viele Optionen
```{R, eval=FALSE}
help(plot.phylo)
```

Wir können die Species "Lynx_canadensis" von dem Baum löschen, da es scheinbar mit der Sequenz Probleme gibt. Wie sieht der Baum jetzt aus?
```{R, eval=FALSE}
tree2 <- drop.tip(tree, "Lynx_canadensis")
tree <- midpoint(tree2)
plot(tree, cex=.75)
plot(tree, type="fan", tip.col=tip_color[tree$tip.label], cex=.5, show.node.label = TRUE)
```


